server:
  port: 8002
spring:
  application:
    name: myconsumer
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
  instance:
    instance-id: myconsumer8002
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true


myprovider:
  ribbon:
     NFLoadBalancerRunleClassName: com.netflix.loadbalancer.RandomRule
