server:
  port: 8004
spring:
  application:
    name: myconsumer
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
  instance:
    instance-id: myconsumer8004
    prefer-ip-address: true
feign:
  hystrix:
    enabled: false


myprovider:
  ribbon:
     NFLoadBalancerRunleClassName: com.netflix.loadbalancer.RandomRule
